### ISSUE TITLE
Byte compilation error seeems to be stopping all Magit functionality

### ISSUE THREAD

**Issue by TriAttack238** [magit/magit#5193]
1. To reproduce, run `M-x magit-version`, `M-x magit`, or `C-x g` in a git repository. 
2. The following error is displayed:
```
comp--native-compile: Native compiler error: (lambda (&rest arg8) (let ((f #'make-process)) (apply f arg8))), "Compiling c:/Users/username/.emacs.d/eln-cache/29.4-a4386b77/subr--trampoline-6d616b652d70726f63657373_make_process_0.eln...
"
```

Oddly enough, magit worked initially in Emacs 29.3 and this issue was originally going to be for the "?" window. But when I updated to 29.4, all of magit now seems to fail. Running emacs with just magit, there is a more verbose error:

GNU Emacs 29.4 (build 2, x86_64-w64-mingw32) of 2024-07-05
```
Debugger entered--Lisp error: (native-compiler-error (lambda (&rest arg0) (let ((f #'make-process)) (apply f arg0))) "Compiling c:/Users/username/.emacs.d/eln-cache/29.4-a...")
  signal(native-compiler-error ((lambda (&rest arg0) (let ((f #'make-process)) (apply f arg0))) "Compiling c:/Users/username/.emacs.d/eln-cache/29.4-a..."))
  comp--native-compile((lambda (&rest arg0) (let ((f #'make-process)) (apply f arg0))) nil "c:/Users/username/.emacs.d/eln-cache/29.4-a4386b77/su...")
  comp-trampoline-compile(make-process)
  comp-subr-trampoline-install(make-process)
  advice--add-function(:around (#f(compiled-function () #<bytecode 0x3c5d8019df7e91>) . #f(compiled-function (gv--val) #<bytecode 0x8fdecbbba7cb3c2>)) make-process@with-editor-process-filter nil)
  advice-add(make-process :around make-process@with-editor-process-filter)
  byte-code("\300\301\302\303#\210\300\304\302\305#\207" [advice-add start-file-process :around start-file-process@with-editor-process-filter make-process make-process@with-editor-process-filter] 4)
  require(with-editor)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\307\310\311\312\313DD\314\315\316\317\320&\7\210\307\321\311\312\322DD\323\324\325\315..." [require magit-base magit-git magit-mode ansi-color auth-source with-editor custom-declare-variable magit-process-connection-type funcall function #f(compiled-function () #<bytecode 0x1e8c725eedbe4a8>) "Connection type used for the Git process.\n\nIf nil,..." :group magit-process :type (choice (const :tag "pipe" nil) (const :tag "pty" t)) magit-need-cygwin-noglob #f(compiled-function () #<bytecode 0x1507f7a3a7cb094b>) "Whether to use a workaround for Cygwin's globbing ..." :package-version (magit . "2.3.0") (choice (const :tag "Yes" t) (const :tag "No" nil)) magit-process-popup-time #f(compiled-function () #<bytecode 0x19800016ff728>) "Popup the process buffer if a command takes longer..." (choice (const :tag "Never" -1) (const :tag "Immediately" 0) (integer :tag "After this many seconds")) magit-process-log-max #f(compiled-function () #<bytecode 0x19800016f3b14>) "Maximum number of sections to keep in a process lo..." (magit . "2.1.0") (choice (const :tag "Never remove old sections" nil) integer)] 10)
  require(magit-process)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\305\306\307\310!\"\210\305\311\312\310!\"\210\305\313\311\"\210\314\313\315\316#\210\317\310\320\311#\321\310\322\323..." [require magit-git magit-mode magit-process transient defalias magit--git-variable-p eieio-make-class-predicate magit--git-variable magit--git-variable--eieio-childp eieio-make-child-predicate magit--git-variable-child-p make-obsolete "use (cl-typep ... 'magit--git-variable) instead" "25.1" define-symbol-prop cl-deftype-satisfies eieio-defclass-internal (transient-variable) ((scope :initarg :scope) (global :initarg :global :initform nil) (default :initarg :default :initform nil)) nil] 6)
  require(magit-transient)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\304\305\306\307\310\311\312\313&\7\207" [require magit-base magit-transient magit-mode custom-declare-group magit-margin nil "Information Magit displays in the margin.\n\nYou can..." :link (info-link "(magit)Log Margin") :group magit-log] 8)
  require(magit-margin)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\310\311\312\313\314\315\314\316\314\317\320\321&\13\210\310\322\312\323\314\324\320..." [require magit-base magit-git magit-mode magit-margin magit-process magit-transient magit-autorevert custom-declare-group magit nil "Controlling Git from Emacs." :link (url-link "https://magit.vc") (info-link "(magit)FAQ") (info-link "(magit)") :group tools magit-essentials "Options that every Magit user should briefly think..." (info-link "(magit)Essential Settings") magit-miscellaneous "Miscellaneous Magit options." magit-commands "Options controlling behavior of certain commands." magit-modes "Modes used or provided by Magit." magit-buffers "Options concerning Magit buffers." (info-link "(magit)Modes and Buffers") magit-refresh "Options controlling how Magit buffers are refreshe..." (info-link "(magit)Automatic Refreshing of Magit Buffers") magit-faces "Faces used by Magit." faces custom-add-to-group diff-refine-added custom-face diff-refine-removed magit-extensions "Extensions to Magit." git-commit custom-group git-commit-faces git-rebase git-rebase-faces magit-section magit-section-faces with-editor ...] 18)
  require(magit-core)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311\312\313#\210\300\314!\210\315\316\317\320\321DD\322..." [require magit-core magit-diff magit-log magit-wip magit-apply magit-repos git-commit format-spec package nil t with-editor custom-declare-variable magit-openpgp-default-signing-key funcall function #f(compiled-function () #<bytecode 0x19800016fe914>) "Fingerprint of your default Openpgp key used for s..." :package-version (magit . "4.0.0") :group magit-commands :type string] 10)
  command-line-1(("--eval" "(setq debug-on-error t)" "-L" "c:/Users/username/.emacs.d/elpaca/builds/compat/" "-L" "c:/Users/username/.emacs.d/elpaca/builds/dash/" "-L" "c:/Users/username/.emacs.d/elpaca/builds/transient/" "-L" "c:/Users/username/.emacs.d/elpaca/builds/with-editor/" "-L" "c:/Users/username/.emacs.d/elpaca/builds/magit/" "-L" "c:/Users/username/.emacs.d/elpaca/builds/magit-sectio..." "-L" "c:/Users/username/.emacs.d/elpaca/builds/git-commit/" "-l" "c:/Users/username/.emacs.d/elpaca/builds/magit/magit"))
  command-line()
  normal-top-level()

```
